from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any


DEFAULT_SUMMARY_DIR = Path("reports/paper_protocol_summary")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary-dir", type=Path, default=DEFAULT_SUMMARY_DIR)
    parser.add_argument("--out-md", type=Path, default=DEFAULT_SUMMARY_DIR / "checkpoint_policy_report.md")
    parser.add_argument("--out-json", type=Path, default=DEFAULT_SUMMARY_DIR / "checkpoint_policy_report.json")
    args = parser.parse_args()

    report = build_report(args.summary_dir)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    md = render_markdown(report)
    args.out_md.write_text(md, encoding="utf-8")
    print(md)


def build_report(summary_dir: Path) -> dict[str, Any]:
    safety = _load_json(summary_dir / "safety_selection_report.json") or {}
    live_run, live = _select_live_diagnosis(summary_dir)
    summary = _load_json(summary_dir / "paper_protocol_summary.json") or {}
    core = summary.get("core_ablation", []) if isinstance(summary, dict) else []
    incomplete_core = [row.get("method") for row in core if row.get("status") != "complete"]
    complete_core = [row.get("method") for row in core if row.get("status") == "complete"]
    safety_rows = safety.get("rows", []) if isinstance(safety, dict) else []
    complete_safety = [row for row in safety_rows if row.get("status") == "complete"]

    latest = live.get("latest_epoch") or {}
    best_loss = live.get("best_val_loss_epoch") or {}
    best_safety = live.get("best_safety_proxy_epoch") or {}
    signals = live.get("signals") or {}

    return {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "summary_dir": str(summary_dir),
        "policy": {
            "main_ablation_table": "Use the loss-selected `best.pt` checkpoint generated by the training protocol.",
            "supplemental_safety_analysis": "Use `best_safety.pt` only in supplemental safety/interval analysis after the main row exists.",
            "final_method_selection": "Rank final candidates by the predeclared multi-metric safety/generalization score, not by manual checkpoint cherry-picking.",
            "claim_boundary": "Do not replace a main-table result with a safety checkpoint unless the protocol is changed before rerunning all affected methods.",
        },
        "core_status": {
            "complete_methods": complete_core,
            "incomplete_methods": incomplete_core,
        },
        "safety_status": {
            "verdict": safety.get("verdict"),
            "num_rows": len(safety_rows),
            "num_complete": len(complete_safety),
            "complete_methods": [row.get("method") for row in complete_safety],
        },
        "live_checkpoint": {
            "run": live_run,
            "latest_epoch": latest.get("epoch"),
            "best_val_loss_epoch": best_loss.get("epoch"),
            "best_safety_proxy_epoch": best_safety.get("epoch"),
            "latest_val_loss": latest.get("val_loss"),
            "best_val_loss": best_loss.get("val_loss"),
            "best_safety_val_loss": best_safety.get("val_loss"),
            "latest_risk_acc": latest.get("val_risk_acc"),
            "best_loss_risk_acc": best_loss.get("val_risk_acc"),
            "best_safety_risk_acc": best_safety.get("val_risk_acc"),
            "latest_raw_coverage": latest.get("raw_coverage"),
            "best_loss_raw_coverage": best_loss.get("raw_coverage"),
            "best_safety_raw_coverage": best_safety.get("raw_coverage"),
            "validation_degradation_flag": signals.get("validation_degradation_flag"),
            "coverage_degradation_flag": signals.get("coverage_degradation_flag"),
        },
        "pipeline_trace": _checkpoint_pipeline_trace(Path(".")),
        "audit_rules": [
            "The P0 table is incomplete until `Full model` has main test, calibration, bootstrap, and audit artifacts.",
            "Safety checkpoint results must be displayed as deltas from the corresponding main checkpoint.",
            "A safety checkpoint that improves coverage but degrades risk F1 or low-friction recall cannot replace the main checkpoint.",
            "All checkpoint policy decisions must be applied consistently to LODO, fair baselines, candidates, and final-method runs.",
        ],
    }


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Checkpoint Policy Report",
        "",
        f"Generated at: {report['generated_at']}",
        "",
        "## Policy",
        "",
    ]
    for key, value in report["policy"].items():
        lines.append(f"- `{key}`: {value}")

    core = report["core_status"]
    safety = report["safety_status"]
    live = report["live_checkpoint"]
    trace = report.get("pipeline_trace") or {}
    lines.extend(
        [
            "",
            "## Current Status",
            "",
            f"- P0 complete methods: {', '.join(f'`{item}`' for item in core.get('complete_methods', [])) or '-'}",
            f"- P0 incomplete methods: {', '.join(f'`{item}`' for item in core.get('incomplete_methods', [])) or '-'}",
            f"- Safety report verdict: `{safety.get('verdict')}`; complete safety rows `{safety.get('num_complete')}/{safety.get('num_rows')}`.",
            "",
            f"## Live Checkpoint Split: `{live.get('run') or '-'}`",
            "",
            "| Scope | Epoch | val loss | risk acc | raw coverage |",
            "|---|---:|---:|---:|---:|",
            "| latest | {latest_epoch} | {latest_loss} | {latest_risk} | {latest_cov} |".format(
                latest_epoch=live.get("latest_epoch") or "-",
                latest_loss=_fmt_abs(live.get("latest_val_loss")),
                latest_risk=_fmt_pct(live.get("latest_risk_acc")),
                latest_cov=_fmt_pct(live.get("latest_raw_coverage")),
            ),
            "| best val loss | {epoch} | {loss} | {risk} | {cov} |".format(
                epoch=live.get("best_val_loss_epoch") or "-",
                loss=_fmt_abs(live.get("best_val_loss")),
                risk=_fmt_pct(live.get("best_loss_risk_acc")),
                cov=_fmt_pct(live.get("best_loss_raw_coverage")),
            ),
            "| best safety proxy | {epoch} | {loss} | {risk} | {cov} |".format(
                epoch=live.get("best_safety_proxy_epoch") or "-",
                loss=_fmt_abs(live.get("best_safety_val_loss")),
                risk=_fmt_pct(live.get("best_safety_risk_acc")),
                cov=_fmt_pct(live.get("best_safety_raw_coverage")),
            ),
            "",
            "## Pipeline Trace",
            "",
            "| Check | Verdict | Evidence |",
            "|---|---|---|",
            "| Main eval uses loss-selected checkpoint | `{main}` | {main_evidence} |".format(
                main=trace.get("main_eval_uses_best"),
                main_evidence=trace.get("main_eval_evidence", "-"),
            ),
            "| Main eval avoids resume checkpoint | `{last}` | {last_evidence} |".format(
                last=trace.get("main_eval_avoids_last"),
                last_evidence=trace.get("main_eval_last_evidence", "-"),
            ),
            "| Safety eval is supplemental | `{safety}` | {safety_evidence} |".format(
                safety=trace.get("safety_eval_supplemental"),
                safety_evidence=trace.get("safety_eval_evidence", "-"),
            ),
            "",
            "## Audit Rules",
            "",
        ]
    )
    for item in report["audit_rules"]:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)


def _fmt_pct(value: Any) -> str:
    num = _num(value)
    if num is None:
        return "-"
    return f"{100.0 * num:.2f}"


def _fmt_abs(value: Any) -> str:
    num = _num(value)
    if num is None:
        return "-"
    return f"{num:.4f}"


def _num(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _load_json(path: Path) -> Any:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _select_live_diagnosis(summary_dir: Path) -> tuple[str | None, dict[str, Any]]:
    active = _load_json(summary_dir / "active_training_watch_report.json") or {}
    active_run = ((active.get("active") or {}).get("name") or active.get("run")) if isinstance(active, dict) else None
    candidates = []
    if active_run:
        candidates.append(str(active_run))
    candidates.append("v5_full_faf")
    for run in candidates:
        path = summary_dir / f"{run}_training_diagnosis.json"
        if path.exists():
            return run, _load_json(path) or {}
    return active_run, {}


def _checkpoint_pipeline_trace(source_root: Path) -> dict[str, Any]:
    direct_path = source_root / "scripts" / "run_paper_protocol_direct.py"
    safety_path = source_root / "scripts" / "backfill_safety_checkpoint_metrics.py"
    direct = _read_text(direct_path)
    safety = _read_text(safety_path)

    main_eval_uses_best = all(
        token in direct
        for token in [
            'best = output_dir / "best.pt"',
            "def _run_eval_pipeline(",
            "--checkpoint",
            "str(best)",
            "scripts/evaluate.py",
            "scripts/evaluate_detailed.py",
            "scripts/calibrate_intervals.py",
            "scripts/bootstrap_metrics.py",
        ]
    )
    eval_section = direct.split("def _run_eval_pipeline(", 1)[1] if "def _run_eval_pipeline(" in direct else direct
    eval_section = eval_section.split("def _confusion(", 1)[0]
    main_eval_avoids_last = "str(last)" not in eval_section and "last.pt" not in eval_section

    safety_eval_supplemental = all(
        token in safety
        for token in [
            'ckpt = run_dir / "best_safety.pt"',
            "not _main_ready(run_dir)",
            "safety_selected",
            "safety-selected evaluations waiting for main artifacts",
        ]
    )
    return {
        "source_files": [str(direct_path), str(safety_path)],
        "main_eval_uses_best": "pass" if main_eval_uses_best else "block",
        "main_eval_evidence": "`run_paper_protocol_direct.py` sets `best = output_dir / \"best.pt\"` and passes `str(best)` to evaluate/detailed/calibration/bootstrap.",
        "main_eval_avoids_last": "pass" if main_eval_avoids_last else "block",
        "main_eval_last_evidence": "`last.pt` is used only for resume/cleanup, not inside `_run_eval_pipeline`.",
        "safety_eval_supplemental": "pass" if safety_eval_supplemental else "block",
        "safety_eval_evidence": "`backfill_safety_checkpoint_metrics.py` evaluates `best_safety.pt` under `safety_selected/` and waits for main artifacts by default.",
    }


def _read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


if __name__ == "__main__":
    main()
