from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEFAULT_SUMMARY_DIR = Path("reports/paper_protocol_summary")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary-dir", type=Path, default=DEFAULT_SUMMARY_DIR)
    parser.add_argument("--out-tex", type=Path, default=DEFAULT_SUMMARY_DIR / "paper_tables.tex")
    parser.add_argument("--out-md", type=Path, default=DEFAULT_SUMMARY_DIR / "paper_tables_index.md")
    args = parser.parse_args()

    report = build_report(args.summary_dir)
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(render_latex(report), encoding="utf-8")
    args.out_md.write_text(render_markdown(report), encoding="utf-8")
    print(render_markdown(report))


def build_report(summary_dir: Path) -> dict[str, Any]:
    return {
        "summary_dir": str(summary_dir),
        "summary": _load_json(summary_dir / "paper_protocol_summary.json") or {},
        "p0_claim": _load_json(summary_dir / "p0_claim_report.json") or {},
        "fair": _load_json(summary_dir / "fair_comparison_report.json") or {},
        "lodo": _load_json(summary_dir / "lodo_generalization_report.json") or {},
        "readiness": _load_json(summary_dir / "topvenue_readiness_gate.json") or {},
    }


def render_latex(report: dict[str, Any]) -> str:
    summary = report["summary"]
    p0_claim = report["p0_claim"]
    fair = report["fair"]
    lodo = report["lodo"]
    readiness = report["readiness"]
    lines = [
        "% Auto-generated by scripts/write_latex_paper_tables.py",
        "% Requires: \\usepackage{booktabs}",
        "% Values are percentages except calibrated width, which is in friction-coefficient units.",
        "",
        _p0_table(p0_claim or summary),
        "",
        _lodo_table(lodo or summary),
        "",
        _fair_table(fair),
        "",
        _final_tables(summary),
        "",
        _readiness_table(readiness),
        "",
    ]
    return "\n".join(lines)


def _p0_table(payload: dict[str, Any]) -> str:
    rows = payload.get("rows") or payload.get("core_ablation", [])
    rows = rows[:6]
    body = []
    for row in rows:
        body.append(
            " & ".join(
                [
                    _tex(row.get("method")),
                    _fmt_ci(row, "friction_macro_f1", fallback="friction_f1"),
                    _fmt_ci(row, "risk_macro_f1", fallback="risk_f1"),
                    _fmt_ci(row, "low_friction_recall"),
                    _fmt_ci(row, "calibrated_coverage"),
                    _fmt_abs_ci(row, "calibrated_width"),
                    _fmt_pct(row.get("worst_dataset_f1")),
                ]
            )
            + r" \\"
        )
    return "\n".join(
        [
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Core P0 ablation. F1, recall, and coverage are percentages; calibrated width is reported in friction-coefficient units.}",
            r"\label{tab:p0-ablation}",
            r"\small",
            r"\begin{tabular}{lrrrrrr}",
            r"\toprule",
            r"Method & Friction F1 & Risk F1 & Low recall & Cal. cov. & Cal. width & Worst F1 \\",
            r"\midrule",
            *body,
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )


def _lodo_table(payload: dict[str, Any]) -> str:
    rows = payload.get("rows") or payload.get("lodo", [])
    body = []
    for row in rows:
        method = row.get("held_out") or row.get("method")
        body.append(
            " & ".join(
                [
                    _tex(method),
                    _tex(row.get("status")),
                    _fmt_pct(row.get("friction_f1", row.get("friction_macro_f1"))),
                    _fmt_pct(row.get("risk_f1", row.get("risk_macro_f1"))),
                    _fmt_pct(row.get("low_friction_recall")),
                    _fmt_pct(row.get("calibrated_coverage")),
                    _fmt_abs(row.get("calibrated_width")),
                ]
            )
            + r" \\"
        )
    return "\n".join(
        [
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Leave-one-dataset-out generalization. Held-out RoadSaW is the primary wet-road domain-shift stress test.}",
            r"\label{tab:lodo}",
            r"\small",
            r"\begin{tabular}{llrrrrr}",
            r"\toprule",
            r"Held-out & Status & Friction F1 & Risk F1 & Low recall & Cal. cov. & Cal. width \\",
            r"\midrule",
            *(body or [r"-- & missing & -- & -- & -- & -- & -- \\"]),
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )


def _fair_table(payload: dict[str, Any]) -> str:
    rows = payload.get("rows", []) if isinstance(payload, dict) else []
    body = []
    for row in rows:
        body.append(
            " & ".join(
                [
                    _tex(row.get("dataset")),
                    _tex(row.get("status")),
                    _fmt_pct(row.get("faf_risk_f1")),
                    _fmt_pct(row.get("baseline_risk_f1")),
                    _fmt_delta_ci(row, "paired_risk_f1_delta"),
                    _fmt_pct(row.get("faf_friction_f1")),
                    _fmt_pct(row.get("baseline_friction_f1")),
                    _fmt_delta_ci(row, "paired_friction_f1_delta"),
                ]
            )
            + r" \\"
        )
    return "\n".join(
        [
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Direct single-dataset fair comparison against matched global ConvNeXt baselines. Deltas are paired bootstrap FAF minus baseline.}",
            r"\label{tab:fair-single-dataset}",
            r"\small",
            r"\begin{tabular}{llrrrrrr}",
            r"\toprule",
            r"Dataset & Status & FAF risk & Base risk & $\Delta$ risk & FAF friction & Base friction & $\Delta$ friction \\",
            r"\midrule",
            *(body or [r"-- & pending & -- & -- & -- & -- & -- & -- \\"]),
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )


def _final_tables(summary: dict[str, Any]) -> str:
    lodo_rows = summary.get("final_lodo", [])
    single_rows = summary.get("final_fair_single_dataset_deltas", [])
    lodo_body = [
        " & ".join(
            [
                _tex(row.get("method")),
                _tex(row.get("status")),
                _fmt_pct(row.get("risk_macro_f1")),
                _fmt_pct(row.get("low_friction_recall")),
                _fmt_pct(row.get("calibrated_coverage")),
                _fmt_abs(row.get("calibrated_width")),
            ]
        )
        + r" \\"
        for row in lodo_rows
    ]
    single_body = [
        " & ".join(
            [
                _tex(row.get("dataset")),
                _tex(row.get("status")),
                _fmt_delta(row.get("delta_risk_macro_f1")),
                _fmt_delta(row.get("delta_low_friction_recall")),
                _fmt_delta(row.get("delta_calibrated_coverage")),
            ]
        )
        + r" \\"
        for row in single_rows
    ]
    return "\n".join(
        [
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Final lean road-ROI safety method evidence.}",
            r"\label{tab:final-method}",
            r"\small",
            r"\begin{tabular}{llrrrr}",
            r"\toprule",
            r"Final LODO row & Status & Risk F1 & Low recall & Cal. cov. & Cal. width \\",
            r"\midrule",
            *(lodo_body or [r"-- & pending & -- & -- & -- & -- \\"]),
            r"\bottomrule",
            r"\end{tabular}",
            "",
            r"\vspace{0.75em}",
            r"\begin{tabular}{llrrr}",
            r"\toprule",
            r"Dataset & Status & $\Delta$ risk & $\Delta$ low recall & $\Delta$ cal. cov. \\",
            r"\midrule",
            *(single_body or [r"-- & pending & -- & -- & -- \\"]),
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )


def _readiness_table(payload: dict[str, Any]) -> str:
    gates = payload.get("gates", []) if isinstance(payload, dict) else []
    selected = [
        gate
        for gate in gates
        if gate.get("level") == "block"
        or gate.get("name")
        in {
            "raw_interval_coverage",
            "calibrated_interval_quality",
            "dataset_shortcut",
            "p1_style_augmentation_candidate_readiness",
            "p3_interval_candidate_readiness",
        }
    ]
    body = []
    for gate in selected[:12]:
        body.append(
            " & ".join(
                [
                    _tex(gate.get("level")),
                    _tex(gate.get("name")),
                    _tex(gate.get("message")),
                ]
            )
            + r" \\"
        )
    return "\n".join(
        [
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Strict readiness gates used before making paper-level claims.}",
            r"\label{tab:readiness-gates}",
            r"\small",
            r"\begin{tabular}{lll}",
            r"\toprule",
            r"Level & Gate & Meaning \\",
            r"\midrule",
            *(body or [r"-- & -- & -- \\"]),
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )


def render_markdown(report: dict[str, Any]) -> str:
    readiness = report.get("readiness", {})
    summary = report.get("summary", {})
    lines = [
        "# Paper Table LaTeX Index",
        "",
        f"Summary dir: `{report['summary_dir']}`",
        "",
        "Generated tables:",
        "",
        "- `tab:p0-ablation`: core P0 ablation with CI where available.",
        "- `tab:lodo`: leave-one-dataset-out generalization.",
        "- `tab:fair-single-dataset`: matched FAF vs ConvNeXt single-dataset comparison.",
        "- `tab:final-method`: final lean-method evidence.",
        "- `tab:readiness-gates`: strict claim-readiness gates.",
        "",
        f"Readiness verdict: `{readiness.get('verdict', '-')}`.",
        f"Core P0 rows: `{_complete_count(summary.get('core_ablation', []))}` complete.",
        f"LODO rows: `{_complete_count(summary.get('lodo', []))}` complete.",
        f"Fair delta rows: `{_complete_count(summary.get('fair_single_dataset_deltas', []))}` complete.",
        "",
        "Output TeX: `reports/paper_protocol_summary/paper_tables.tex`",
        "",
    ]
    return "\n".join(lines)


def _fmt_ci(row: dict[str, Any], key: str, *, fallback: str | None = None) -> str:
    value = row.get(key)
    if value is None and fallback is not None:
        value = row.get(fallback)
    if value is None:
        return "--"
    low = row.get(f"{key}_ci_low")
    high = row.get(f"{key}_ci_high")
    if low is None or high is None:
        return _fmt_pct(value)
    return f"{_fmt_pct(value)} [{_fmt_pct(low)}, {_fmt_pct(high)}]"


def _fmt_abs_ci(row: dict[str, Any], key: str) -> str:
    value = row.get(key)
    if value is None:
        return "--"
    low = row.get(f"{key}_ci_low")
    high = row.get(f"{key}_ci_high")
    if low is None or high is None:
        return _fmt_abs(value)
    return f"{_fmt_abs(value)} [{_fmt_abs(low)}, {_fmt_abs(high)}]"


def _fmt_delta_ci(row: dict[str, Any], key: str) -> str:
    value = row.get(key)
    if value is None:
        return "--"
    low = row.get(f"{key}_ci_low")
    high = row.get(f"{key}_ci_high")
    if low is None or high is None:
        return _fmt_delta(value)
    return f"{_fmt_delta(value)} [{_fmt_delta(low)}, {_fmt_delta(high)}]"


def _fmt_pct(value: Any) -> str:
    num = _num(value)
    if num is None:
        return "--"
    return f"{100.0 * num:.2f}"


def _fmt_delta(value: Any) -> str:
    num = _num(value)
    if num is None:
        return "--"
    return f"{100.0 * num:+.2f}"


def _fmt_abs(value: Any) -> str:
    num = _num(value)
    if num is None:
        return "--"
    return f"{num:.4f}"


def _tex(value: Any) -> str:
    if value is None or value == "":
        return "--"
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for raw, repl in replacements.items():
        text = text.replace(raw, repl)
    return text


def _complete_count(rows: list[dict[str, Any]]) -> str:
    complete = sum(1 for row in rows if row.get("status") == "complete")
    return f"{complete}/{len(rows)}" if rows else "0/0"


def _num(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _load_json(path: Path) -> Any:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
